# Generated by Django 6.0.1 on 2026-01-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('physics_ikt', models.IntegerField(verbose_name='Балл Физика/ИКТ')),
                ('russian_lang', models.IntegerField(verbose_name='Балл Русский язык')),
                ('math', models.IntegerField(verbose_name='Балл Математика')),
                ('achievements', models.IntegerField(verbose_name='Балл за индивидуальные достижения')),
                ('total_score', models.IntegerField(verbose_name='Сумма баллов')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
            },
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('seats', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='AdmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('has_consent', models.BooleanField(verbose_name='Наличие согласия о зачислении')),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Приоритет ОП')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_api.applicant', verbose_name='Абитуриент')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_api.educationalprogram', verbose_name='Образовательная программа')),
            ],
            options={
                'verbose_name': 'Запись о поступлении',
                'verbose_name_plural': 'Записи о поступлении',
                'unique_together': {('applicant', 'educational_program', 'date')},
            },
        ),
    ]
